// src/config/permissions.js

export const ROLES = {
  //   SUPERADMIN: "superadmin",
  MANAGER: "manager",
  BOSHQARMA: "boshqarma",
  VIEWER: "viewer",
  XODIM: "xodim",
  rais: "rais",
};

export const PERMISSIONS = {
  superadmin: {
    canCreate: true,
    canRead: true,
    canUpdate: true,
    canDelete: true,
    canManageUsers: true,
    canSeeUsers: true,
    canSeeBoshqarmalar: true,
    canCreateChatXonalar: true,
    canSeeXodimlar: true,
    canSeeBoshSahifa: true,
    canCreateBoshqarma: true,
    canSeeAllBoshqarmalar: true,
    canDeleteHujjat: true,
    canEditHujjat: true,
    canDeleteTopshiriq: true,
    canSeeKategoriyaMenu: true,
    canEditObyekt: true,
    canSeeRahbariyatLavozim: true,
  },
  rais: {
    canCreate: true,
    canRead: true,
    canUpdate: true,
    canDelete: true,
    canManageUsers: true,
    canSeeBoshqarmalar: true,
    rais: true,
    canCreateChatXonalar: true,
    canSeeXodimlar: true,
    canSeeBoshSahifa: true,
    canCreateBoshqarma: true,
    canSeeAllBoshqarmalar: true,
    canDeleteHujjat: true,
    canDeleteTopshiriq: true,
    canSeeKategoriyaMenu: true,
    canEditObyekt: true,
    canSeeRahbariyatLavozim: true,
  },
  rais_orinbosari: {
    canCreate: false,
    canCreateTopshiriq: false,
    canCreateBayonnoma: false,
    canRead: true,
    canUpdate: true,
    canDelete: false,
    canManageUsers: true,
    canSeeUsers: false,
    canSeeBoshqarmalar: true,
    canSeeBoshSahifa: true,
    canSeeAllBoshqarmalar: true,
    canEditObyekt: true,
    canSeeRahbariyatLavozim: false,
  },
  boshqarma_boshi: {
    canCreate: true,
    canRead: true,
    canUpdate: true,
    canDelete: false,
    canManageUsers: true,
    canSeeBoshqarmalar: true,
    canCreateChatXonalar: false,
    canSeeXodimlar: true,
    canSeeBoshSahifa: false,
    canCreateBoshqarma: false,
    canSeeAllBoshqarmalar: false,
    canDeleteHujjat: true,
    canEditHujjat: true,
    canDeleteTopshiriq: false,
    canSeeKategoriyaMenu: true,
    canEditObyekt: false,
    canSeeRahbariyatLavozim: false,
  },
  pto: {
    canCreate: false,
    canRead: true,
    canUpdate: false,
    canDelete: false,
    canManageUsers: false,
    canCreateTalab: true,
    canSeeTalablar: true,
    canSeeBoshqarmalar: true,
    canDeleteHujjat: false,
    canEditHujjat: false,
    canDeleteTopshiriq: false,
    canSeeKategoriyaMenu: false,
    canSeeRahbariyatLavozim: false,
  },
  boshqarma: {
    canCreate: true,
    canRead: true,
    canUpdate: false,
    canDelete: false,
    canManageUsers: false,
  },
  xodim: {
    canCreate: false,
    canRead: true,
    canUpdate: false,
    canDelete: false,
    canManageUsers: false,
    canCreateTalab: true,
  },
  viewer: {
    canCreate: false,
    canRead: true,
    canUpdate: false,
    canDelete: false,
    canManageUsers: false,
  },
};
